slow:Java exceptions AssertionError in another Thread is rethrown on the main Ruby Thread
