fails:Enumerator::Lazy#reject lets exceptions raised in the block go through
